In [1]:
import tensorflow as tf
import pandas as pd
from sklearn.model_selection import train_test_split
from tensorflow.keras import layers

In [2]:
data = pd.read_csv('/home/lindo/Data/NLP/Marito/st_imbd')
X = data['st']
y = data['sentiment']

In [3]:
X[10000]

'Filimi e nyahamisang'

In [4]:
y[10000]

-0.6

In [5]:
num_words = 10000

In [6]:
tokenizer = tf.keras.preprocessing.text.Tokenizer(num_words = 10000)

In [7]:
tokenizer.fit_on_texts(X)

In [8]:
tokenizer.word_index

{'e': 1,
 'ho': 2,
 'le': 3,
 'ka': 4,
 'ke': 5,
 'ea': 6,
 'ba': 7,
 'a': 8,
 'o': 9,
 'ha': 10,
 'tse': 11,
 'sa': 12,
 'se': 13,
 'hore': 14,
 'oa': 15,
 'ne': 16,
 'tsa': 17,
 'na': 18,
 'filimi': 19,
 'li': 20,
 'ena': 21,
 'haholo': 22,
 'empa': 23,
 'hae': 24,
 'mme': 25,
 'eo': 26,
 'bona': 27,
 'u': 28,
 'la': 29,
 'joalo': 30,
 'ntle': 31,
 'kapa': 32,
 'etsa': 33,
 're': 34,
 'bo': 35,
 'pele': 36,
 'tla': 37,
 'mong': 38,
 'feela': 39,
 "'me": 40,
 'eona': 41,
 'ile': 42,
 'nako': 43,
 'hantle': 44,
 'batho': 45,
 'lifilimi': 46,
 'motho': 47,
 'neng': 48,
 'sena': 49,
 "'ngoe": 50,
 'bakeng': 51,
 'ntse': 52,
 'ebile': 53,
 'baesekopo': 54,
 'feta': 55,
 'seo': 56,
 'ntho': 57,
 'nang': 58,
 'haeba': 59,
 'pale': 60,
 'mpe': 61,
 'mo': 62,
 'ling': 63,
 'nahana': 64,
 'monate': 65,
 'leha': 66,
 'ngata': 67,
 'maikutlo': 68,
 'shebella': 69,
 'mokhoa': 70,
 'hape': 71,
 'mofuta': 72,
 'nka': 73,
 'karolo': 74,
 'fumana': 75,
 'moo': 76,
 'tsoa': 77,
 'be': 78,
 'batla': 79

In [9]:
len(tokenizer.word_index)

102986

In [10]:
X_tokens = tokenizer.texts_to_sequences(X)

In [11]:
X_tokens

[[],
 [],
 [],
 [2, 6832, 10, 2854],
 [],
 [466, 197, 30, 4, 1, 221, 1, 478, 3, 3788, 1, 30],
 [540],
 [7992],
 [5897],
 [6313],
 [399],
 [581, 11, 399, 17, 112, 7, 141, 7, 2, 69, 19, 21, 13, 5, 15],
 [399],
 [450],
 [450, 2, 11, 310],
 [891],
 [294,
  11,
  660,
  17,
  1338,
  3,
  543,
  7,
  2,
  1278,
  150,
  7,
  208,
  2,
  6073,
  4,
  3809,
  21],
 [187, 1, 618],
 [1120],
 [1120],
 [1684, 13, 169, 2, 6120],
 [1919, 15, 1399, 9, 230, 2279, 2, 278, 653, 29, 4766, 32, 2, 248],
 [493, 1, 16, 1, 12, 8863, 5349, 4, 286, 2, 371, 1, 3, 50],
 [446, 35, 621, 2, 828, 4, 716, 3403, 35, 3789, 5, 548],
 [661, 7, 46, 7, 371, 54, 1, 207, 6, 140],
 [139, 12, 1326, 13, 4453, 1158, 6, 677, 26, 7, 1, 1481, 4, 1048],
 [12, 1478, 12, 5677, 3, 2116, 6, 5278, 3, 4, 1207, 1, 597, 19, 6, 141, 2],
 [623, 6, 2763, 645, 4250],
 [579,
  6,
  436,
  6,
  4390,
  3094,
  17,
  1500,
  15,
  24,
  9,
  5586,
  4,
  286,
  481,
  288,
  124,
  3,
  1,
  50],
 [1, 3, 50, 1, 16, 1, 5, 5, 6, 1151, 2, 761, 4, 377

In [12]:
atokenizer = dict(map(reversed, tokenizer.word_index.items()))

In [13]:
len(atokenizer)

102986

In [14]:
y = y.values

In [15]:
X_train, X_test, y_train, y_test = train_test_split(X_tokens, y, test_size=0.33, random_state=42)

In [16]:
X_tokens[1000]

[39, 28, 13, 5, 335, 266, 43, 6, 141, 6, 178, 4, 1669, 49, 13, 13, 58, 334]

In [17]:
X[1000]

'- feela u se ke ua senya nako ea hau ea bohlokoa ka sengoathoana sena se se nang thuso'

In [18]:
sentence_lengths = X.str.split().apply(len)

In [19]:
max(sentence_lengths)

32403

In [20]:
import numpy as np

In [21]:
np.mean(sentence_lengths) +np.std(sentence_lengths)

45.02718454758962

In [22]:
np.sum(sentence_lengths < 20)/len(sentence_lengths)

0.8785526780495563

In [23]:
X_train = tf.keras.preprocessing.sequence.pad_sequences(X_train, maxlen = 20, padding = 'pre', truncating = 'pre')

In [24]:
X_train

array([[   0,    0,    0, ...,    4, 3370, 1148],
       [   0,    0,    0, ...,   36,    2, 4985],
       [ 118,  119,   20, ...,  105,   17,   41],
       ...,
       [ 107,   15,   24, ...,    1,    6,   95],
       [   0,    0,    0, ...,   12,    3,  243],
       [   0,    0,    0, ...,    7,    2, 2556]], dtype=int32)

In [25]:
#X_train = [[j for j in i] for i in X_train]

In [26]:
X_train[1]

array([   0,    0,    0,    0,    9,  120,    8,   33,  866,    2,    5,
        112,    4, 1170,    6, 2877,    6,   36,    2, 4985], dtype=int32)

In [27]:
y_train[1]

0.0

In [28]:
def atoken(seq):
    out = []
    for key in seq:
        if key >0:
            out.append(atokenizer[key])
    return out

In [29]:
atoken(X_train[1])

['o',
 'hlile',
 'a',
 'etsa',
 'teko',
 'ho',
 'ke',
 'bophelo',
 'ka',
 'kopo',
 'ea',
 'khosana',
 'ea',
 'pele',
 'ho',
 'kopanelo']

In [30]:
model = tf.keras.Sequential([
    tf.keras.layers.Embedding(10000, 64),
    tf.keras.layers.Bidirectional(tf.keras.layers.LSTM(64)),
    tf.keras.layers.Dense(64, activation='relu'),
    tf.keras.layers.Dense(1, activation='tanh')
])

In [31]:
model.compile(loss='mse',
              optimizer=tf.keras.optimizers.Adam(1e-4),
              metrics=['accuracy'])

In [32]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, None, 64)          640000    
_________________________________________________________________
bidirectional (Bidirectional (None, 128)               66048     
_________________________________________________________________
dense (Dense)                (None, 64)                8256      
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 65        
Total params: 714,369
Trainable params: 714,369
Non-trainable params: 0
_________________________________________________________________


In [33]:
len(X_train)

648797

In [34]:
len(y_train)

648797

In [47]:
len(X_test)

319557

In [48]:
len(X_train)

648797

In [ ]:
history = model.fit(X_train, y_train, validation_split = 0.20, epochs = 6)

Train on 519037 samples, validate on 129760 samples
Epoch 1/6
519037/519037 [==============================] - 536s 1ms/sample - loss: 0.0493 - accuracy: 0.4886 - val_loss: 0.0485 - val_accuracy: 0.4910
Epoch 2/6
519037/519037 [==============================] - 591s 1ms/sample - loss: 0.0472 - accuracy: 0.4892 - val_loss: 0.0479 - val_accuracy: 0.4914
Epoch 3/6
324768/519037 [=================>............] - ETA: 3:15 - loss: 0.0456 - accuracy: 0.4893

In [49]:
history.history['loss']

[0.06466079006311082, 0.052577076794547026, 0.04952500612441108]

In [37]:
xt = tf.keras.preprocessing.sequence.pad_sequences(X_test, maxlen = 20, padding = 'pre', truncating = 'pre')

In [38]:
model.save('st_sent.h5')

In [55]:
test = model.predict(xt[0:1000])

In [56]:
test

array([[-2.54086077e-01],
       [ 6.67945147e-02],
       [-4.99506528e-03],
       [ 5.01348913e-01],
       [ 7.57877678e-02],
       [-5.07225329e-03],
       [-3.85584198e-02],
       [-4.13994603e-02],
       [ 7.57870302e-02],
       [-2.47548465e-02],
       [-8.97718593e-02],
       [ 3.44195068e-02],
       [-1.54738724e-02],
       [-4.02656496e-02],
       [-5.08068576e-02],
       [ 6.15358539e-02],
       [ 1.00925602e-01],
       [-1.40067160e-01],
       [ 2.18023539e-01],
       [-1.59639060e-01],
       [-2.62369532e-02],
       [ 9.56624448e-02],
       [-3.47655341e-02],
       [-5.81749916e-01],
       [-4.85242195e-02],
       [ 1.14757016e-01],
       [-3.57874334e-02],
       [ 1.70251504e-01],
       [ 2.11789057e-01],
       [ 5.92164658e-02],
       [-4.98821661e-02],
       [-2.10857820e-02],
       [-4.28956389e-01],
       [-3.29364806e-01],
       [-1.97542742e-01],
       [ 1.26538113e-01],
       [-9.30745527e-02],
       [ 2.94110060e-01],
       [ 1.0

In [53]:
y_test[0:10]

array([-0.1       ,  0.78      ,  0.        , -0.04166667,  0.        ,
        0.        ,  0.15      ,  0.13461538,  0.        ,  0.        ])

In [69]:
k = 0
for i, j in zip(test, y_test[0:1000]):
    if i*j > 0:
        k+=1

In [70]:
k

428